#!/usr/bin/env python3
# Generate research scripts for India, China, Turkey, and Russia
import json

# Country configurations
COUNTRIES = {
    'India': {
        'currency': 'INR',
        'regions': [
            {'code': 'AP', 'name': 'Andhra Pradesh'}, {'code': 'AR', 'name': 'Arunachal Pradesh'},
            {'code': 'AS', 'name': 'Assam'}, {'code': 'BR', 'name': 'Bihar'},
            {'code': 'CT', 'name': 'Chhattisgarh'}, {'code': 'GA', 'name': 'Goa'},
            {'code': 'GJ', 'name': 'Gujarat'}, {'code': 'HR', 'name': 'Haryana'},
            {'code': 'HP', 'name': 'Himachal Pradesh'}, {'code': 'JH', 'name': 'Jharkhand'},
            {'code': 'KA', 'name': 'Karnataka'}, {'code': 'KL', 'name': 'Kerala'},
            {'code': 'MP', 'name': 'Madhya Pradesh'}, {'code': 'MH', 'name': 'Maharashtra'},
            {'code': 'MN', 'name': 'Manipur'}, {'code': 'ML', 'name': 'Meghalaya'},
            {'code': 'MZ', 'name': 'Mizoram'}, {'code': 'NL', 'name': 'Nagaland'},
            {'code': 'OR', 'name': 'Odisha'}, {'code': 'PB', 'name': 'Punjab'},
            {'code': 'RJ', 'name': 'Rajasthan'}, {'code': 'SK', 'name': 'Sikkim'},
            {'code': 'TN', 'name': 'Tamil Nadu'}, {'code': 'TG', 'name': 'Telangana'},
            {'code': 'TR', 'name': 'Tripura'}, {'code': 'UP', 'name': 'Uttar Pradesh'},
            {'code': 'UK', 'name': 'Uttarakhand'}, {'code': 'WB', 'name': 'West Bengal'},
            {'code': 'AN', 'name': 'Andaman and Nicobar Islands'}, {'code': 'CH', 'name': 'Chandigarh'},
            {'code': 'DN', 'name': 'Dadra and Nagar Haveli and Daman and Diu'}, {'code': 'DL', 'name': 'Delhi'},
            {'code': 'JK', 'name': 'Jammu and Kashmir'}, {'code': 'LA', 'name': 'Ladakh'},
            {'code': 'LD', 'name': 'Lakshadweep'}, {'code': 'PY', 'name': 'Puducherry'}
        ]
    },
    'China': {
        'currency': 'CNY',
        'regions': [
            {'code': 'BJ', 'name': 'Beijing'}, {'code': 'TJ', 'name': 'Tianjin'},
            {'code': 'HE', 'name': 'Hebei'}, {'code': 'SX', 'name': 'Shanxi'},
            {'code': 'NM', 'name': 'Inner Mongolia'}, {'code': 'LN', 'name': 'Liaoning'},
            {'code': 'JL', 'name': 'Jilin'}, {'code': 'HL', 'name': 'Heilongjiang'},
            {'code': 'SH', 'name': 'Shanghai'}, {'code': 'JS', 'name': 'Jiangsu'},
            {'code': 'ZJ', 'name': 'Zhejiang'}, {'code': 'AH', 'name': 'Anhui'},
            {'code': 'FJ', 'name': 'Fujian'}, {'code': 'JX', 'name': 'Jiangxi'},
            {'code': 'SD', 'name': 'Shandong'}, {'code': 'HA', 'name': 'Henan'},
            {'code': 'HB', 'name': 'Hubei'}, {'code': 'HN', 'name': 'Hunan'},
            {'code': 'GD', 'name': 'Guangdong'}, {'code': 'GX', 'name': 'Guangxi'},
            {'code': 'HI', 'name': 'Hainan'}, {'code': 'CQ', 'name': 'Chongqing'},
            {'code': 'SC', 'name': 'Sichuan'}, {'code': 'GZ', 'name': 'Guizhou'},
            {'code': 'YN', 'name': 'Yunnan'}, {'code': 'XZ', 'name': 'Tibet'},
            {'code': 'SN', 'name': 'Shaanxi'}, {'code': 'GS', 'name': 'Gansu'},
            {'code': 'QH', 'name': 'Qinghai'}, {'code': 'NX', 'name': 'Ningxia'},
            {'code': 'XJ', 'name': 'Xinjiang'}, {'code': 'HK', 'name': 'Hong Kong'},
            {'code': 'MO', 'name': 'Macau'}
        ]
    },
    'Turkey': {
        'currency': 'TRY',
        'regions': [
            {'code': '01', 'name': 'Adana'}, {'code': '02', 'name': 'Adıyaman'},
            {'code': '03', 'name': 'Afyonkarahisar'}, {'code': '04', 'name': 'Ağrı'},
            {'code': '05', 'name': 'Amasya'}, {'code': '06', 'name': 'Ankara'},
            {'code': '07', 'name': 'Antalya'}, {'code': '08', 'name': 'Artvin'},
            {'code': '09', 'name': 'Aydın'}, {'code': '10', 'name': 'Balıkesir'},
            {'code': '11', 'name': 'Bilecik'}, {'code': '12', 'name': 'Bingöl'},
            {'code': '13', 'name': 'Bitlis'}, {'code': '14', 'name': 'Bolu'},
            {'code': '15', 'name': 'Burdur'}, {'code': '16', 'name': 'Bursa'},
            {'code': '17', 'name': 'Çanakkale'}, {'code': '18', 'name': 'Çankırı'},
            {'code': '19', 'name': 'Çorum'}, {'code': '20', 'name': 'Denizli'},
            {'code': '21', 'name': 'Diyarbakır'}, {'code': '22', 'name': 'Edirne'},
            {'code': '23', 'name': 'Elazığ'}, {'code': '24', 'name': 'Erzincan'},
            {'code': '25', 'name': 'Erzurum'}, {'code': '26', 'name': 'Eskişehir'},
            {'code': '27', 'name': 'Gaziantep'}, {'code': '28', 'name': 'Giresun'},
            {'code': '29', 'name': 'Gümüşhane'}, {'code': '30', 'name': 'Hakkari'},
            {'code': '31', 'name': 'Hatay'}, {'code': '32', 'name': 'Isparta'},
            {'code': '33', 'name': 'Mersin'}, {'code': '34', 'name': 'Istanbul'},
            {'code': '35', 'name': 'İzmir'}, {'code': '36', 'name': 'Kars'},
            {'code': '37', 'name': 'Kastamonu'}, {'code': '38', 'name': 'Kayseri'},
            {'code': '39', 'name': 'Kırklareli'}, {'code': '40', 'name': 'Kırşehir'},
            {'code': '41', 'name': 'Kocaeli'}, {'code': '42', 'name': 'Konya'},
            {'code': '43', 'name': 'Kütahya'}, {'code': '44', 'name': 'Malatya'},
            {'code': '45', 'name': 'Manisa'}, {'code': '46', 'name': 'Kahramanmaraş'},
            {'code': '47', 'name': 'Mardin'}, {'code': '48', 'name': 'Muğla'},
            {'code': '49', 'name': 'Muş'}, {'code': '50', 'name': 'Nevşehir'},
            {'code': '51', 'name': 'Niğde'}, {'code': '52', 'name': 'Ordu'},
            {'code': '53', 'name': 'Rize'}, {'code': '54', 'name': 'Sakarya'},
            {'code': '55', 'name': 'Samsun'}, {'code': '56', 'name': 'Siirt'},
            {'code': '57', 'name': 'Sinop'}, {'code': '58', 'name': 'Sivas'},
            {'code': '59', 'name': 'Tekirdağ'}, {'code': '60', 'name': 'Tokat'},
            {'code': '61', 'name': 'Trabzon'}, {'code': '62', 'name': 'Tunceli'},
            {'code': '63', 'name': 'Şanlıurfa'}, {'code': '64', 'name': 'Uşak'},
            {'code': '65', 'name': 'Van'}, {'code': '66', 'name': 'Yozgat'},
            {'code': '67', 'name': 'Zonguldak'}, {'code': '68', 'name': 'Aksaray'},
            {'code': '69', 'name': 'Bayburt'}, {'code': '70', 'name': 'Karaman'},
            {'code': '71', 'name': 'Kırıkkale'}, {'code': '72', 'name': 'Batman'},
            {'code': '73', 'name': 'Şırnak'}, {'code': '74', 'name': 'Bartın'},
            {'code': '75', 'name': 'Ardahan'}, {'code': '76', 'name': 'Iğdır'},
            {'code': '77', 'name': 'Yalova'}, {'code': '78', 'name': 'Karabük'},
            {'code': '79', 'name': 'Kilis'}, {'code': '80', 'name': 'Osmaniye'},
            {'code': '81', 'name': 'Düzce'}
        ]
    },
    'Russia': {
        'currency': 'RUB',
        'regions': [
            {'code': 'AD', 'name': 'Republic of Adygea'}, {'code': 'AL', 'name': 'Republic of Altai'},
            {'code': 'BA', 'name': 'Republic of Bashkortostan'}, {'code': 'BU', 'name': 'Republic of Buryatia'},
            {'code': 'CE', 'name': 'Chechen Republic'}, {'code': 'CU', 'name': 'Chuvash Republic'},
            {'code': 'DA', 'name': 'Republic of Dagestan'}, {'code': 'IN', 'name': 'Republic of Ingushetia'},
            {'code': 'KB', 'name': 'Kabardino-Balkarian Republic'}, {'code': 'KL', 'name': 'Republic of Kalmykia'},
            {'code': 'KC', 'name': 'Karachay-Cherkess Republic'}, {'code': 'KR', 'name': 'Republic of Karelia'},
            {'code': 'KH', 'name': 'Republic of Khakassia'}, {'code': 'KO', 'name': 'Komi Republic'},
            {'code': 'ME', 'name': 'Republic of Mari El'}, {'code': 'MO', 'name': 'Republic of Mordovia'},
            {'code': 'SA', 'name': 'Republic of Sakha (Yakutia)'}, {'code': 'SE', 'name': 'Republic of North Ossetia-Alania'},
            {'code': 'TA', 'name': 'Republic of Tatarstan'}, {'code': 'TY', 'name': 'Tuva Republic'},
            {'code': 'UD', 'name': 'Udmurt Republic'}, {'code': 'ALT', 'name': 'Altai Krai'},
            {'code': 'KDA', 'name': 'Krasnodar Krai'}, {'code': 'KYA', 'name': 'Krasnoyarsk Krai'},
            {'code': 'PER', 'name': 'Perm Krai'}, {'code': 'PRI', 'name': 'Primorsky Krai'},
            {'code': 'STA', 'name': 'Stavropol Krai'}, {'code': 'ZAB', 'name': 'Zabaykalsky Krai'},
            {'code': 'AMU', 'name': 'Amur Oblast'}, {'code': 'ARK', 'name': 'Arkhangelsk Oblast'},
            {'code': 'AST', 'name': 'Astrakhan Oblast'}, {'code': 'BEL', 'name': 'Belgorod Oblast'},
            {'code': 'BRY', 'name': 'Bryansk Oblast'}, {'code': 'CHE', 'name': 'Chelyabinsk Oblast'},
            {'code': 'IRK', 'name': 'Irkutsk Oblast'}, {'code': 'IVA', 'name': 'Ivanovo Oblast'},
            {'code': 'KGD', 'name': 'Kaliningrad Oblast'}, {'code': 'KLU', 'name': 'Kaluga Oblast'},
            {'code': 'KEM', 'name': 'Kemerovo Oblast'}, {'code': 'KIR', 'name': 'Kirov Oblast'},
            {'code': 'KOS', 'name': 'Kostroma Oblast'}, {'code': 'KGN', 'name': 'Kurgan Oblast'},
            {'code': 'KRS', 'name': 'Kursk Oblast'}, {'code': 'LEN', 'name': 'Leningrad Oblast'},
            {'code': 'LIP', 'name': 'Lipetsk Oblast'}, {'code': 'MAG', 'name': 'Magadan Oblast'},
            {'code': 'MOS', 'name': 'Moscow Oblast'}, {'code': 'MUR', 'name': 'Murmansk Oblast'},
            {'code': 'NIZ', 'name': 'Nizhny Novgorod Oblast'}, {'code': 'NGR', 'name': 'Novgorod Oblast'},
            {'code': 'NVS', 'name': 'Novosibirsk Oblast'}, {'code': 'OMS', 'name': 'Omsk Oblast'},
            {'code': 'ORE', 'name': 'Orenburg Oblast'}, {'code': 'ORL', 'name': 'Oryol Oblast'},
            {'code': 'PNZ', 'name': 'Penza Oblast'}, {'code': 'PSK', 'name': 'Pskov Oblast'},
            {'code': 'ROS', 'name': 'Rostov Oblast'}, {'code': 'RYA', 'name': 'Ryazan Oblast'},
            {'code': 'SAK', 'name': 'Sakhalin Oblast'}, {'code': 'SAM', 'name': 'Samara Oblast'},
            {'code': 'SAR', 'name': 'Saratov Oblast'}, {'code': 'SMO', 'name': 'Smolensk Oblast'},
            {'code': 'SVE', 'name': 'Sverdlovsk Oblast'}, {'code': 'TAM', 'name': 'Tambov Oblast'},
            {'code': 'TOM', 'name': 'Tomsk Oblast'}, {'code': 'TUL', 'name': 'Tula Oblast'},
            {'code': 'TVE', 'name': 'Tver Oblast'}, {'code': 'TYU', 'name': 'Tyumen Oblast'},
            {'code': 'ULY', 'name': 'Ulyanovsk Oblast'}, {'code': 'VLA', 'name': 'Vladimir Oblast'},
            {'code': 'VGG', 'name': 'Volgograd Oblast'}, {'code': 'VLG', 'name': 'Vologda Oblast'},
            {'code': 'VOR', 'name': 'Voronezh Oblast'}, {'code': 'YAR', 'name': 'Yaroslavl Oblast'},
            {'code': 'MOW', 'name': 'Moscow'}, {'code': 'SPE', 'name': 'Saint Petersburg'},
            {'code': 'SEV', 'name': 'Sevastopol'}, {'code': 'YEV', 'name': 'Jewish Autonomous Oblast'},
            {'code': 'CHU', 'name': 'Chukotka Autonomous Okrug'}, {'code': 'KHM', 'name': 'Khanty-Mansi Autonomous Okrug'},
            {'code': 'NEN', 'name': 'Nenets Autonomous Okrug'}, {'code': 'YAN', 'name': 'Yamalo-Nenets Autonomous Okrug'}
        ]
    }
}

print("Country configurations prepared. Use this data to create scripts.")
